from python:3.10.7

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY . /app
WORKDIR /app

ENTRYPOINT exec pytest -n 15 --cov=tapi --cov-report term-missing

